version: "3.8"

networks:
  leaguesports:

services:
  db:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234 
      MYSQL_DATABASE: db_leaguesports
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - leaguesports

  web1:
    image: ghcr.io/alejandroorejudo2000/leaguesports-webapp:latest
    # build:
    #   context: ./leaguesports
    #   dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
      - restloadbalancer
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      DDL_AUTO: create # solo primer despliegue
      REST_HOST: restloadbalancer
    networks:
      - leaguesports

  web2:
    image: ghcr.io/alejandroorejudo2000/leaguesports-webapp:latest
    # build:
    #   context: ./leaguesports
    #   dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
      - restloadbalancer
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      REST_HOST: restloadbalancer
    networks:
      - leaguesports

  loadbalancer:
    image: haproxy:2.1
    volumes:
      - ./haproxy/haproxy-web.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 8443:8443
      - 8084:8084
    depends_on:
      - web1
      - web2
    networks:
      - leaguesports      

  rest1:
    image: ghcr.io/alejandroorejudo2000/leaguesports-rest:latest
    # build:
    #   context: ./rest
    #   dockerfile: Dockerfile
    networks:
      - leaguesports

  rest2:
    image: ghcr.io/alejandroorejudo2000/leaguesports-rest:latest
    # build:
    #   context: ./rest
    #   dockerfile: Dockerfile
    networks:
      - leaguesports
  
  restloadbalancer:
    image: haproxy:2.1
    volumes:
      - ./haproxy/haproxy-rest.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 8085:8084
    depends_on:
      - rest1
      - rest2
    networks:
      - leaguesports 

volumes:
  dbdata: