@startuml components
package "Control"{
    component MainController as mainctrl
    component PlayerController as playerctrl
    component ProductController as prodctrl
    component TeamController as teamctrl
    component TournamentController as tourctrl
    component UserController as userctrl
    component LoginController as logctrl
}

package "Service"{
    component DataBaseInitializer as dbserv
    component PlayerService as playerserv
    component ProductService as prodserv
    component TeamService as teamserv
    component TournamentService as tourserv
    component UserService as userserv
    component EmailService as emailserv
}

package "Repository"{
    component GameRepository as gamerep
    component PlayerRepository as playerrep
    component ProductRepository as prodrep
    component TeamRepository as teamrep
    component TournamentRepository as tourrep
    component UserRepository as userrep
}

package "Security"{
    component SecurityConfigurer as Securitycomponent 
    component CSRFHandlerAdapter as csrf
}

playerctrl --> playerserv
playerctrl --> teamserv
teamctrl --> teamserv
prodctrl --> prodserv
prodctrl --> emailserv
tourctrl --> tourserv
tourctrl --> emailserv
tourctrl --> userserv
userctrl --> userserv
userctrl --> emailserv
logctrl --> userserv

playerserv --> playerrep
playerserv --> teamserv
prodserv --> prodrep
teamserv --> teamrep
tourserv --> tourrep
tourserv--> gamerep
tourserv --> teamserv

userserv --> userrep


@enduml