name: Build Docker Image for Rest

on:
  push:
    branches: [ main ]
    paths:
      - 'rest/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: step1
      run: echo ${{ secrets.PAT }} | docker login ghcr.io -u alejandroorejudo2000 --password-stdin 
    - id: step2
      run: docker build -t ghcr.io/alejandroorejudo2000/leaguesports-rest ./rest
    - id: step3
      run: docker push hcr.io/alejandroorejudo2000/leaguesports-rest
